name: demo job
run-name: This action has been run

on: [push]

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Add dotnet-format
        uses: actions/setup-dotnet@v5
        with:
           dotnet-version: '10.0.x'

      - run: dotnet format
