name: demo job
run-name: This action has been run

on: [push]

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: CodeQL Bundle
        uses: advanced-security/codeql-bundle-action@v1.1.0

      - name: Dependency Review
        uses: actions/dependency-review-action@v4.8.2
